id: A81299E2E
title: A Method of Confessing and Pledging through the Four Powers
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:18:42.031221
  last_modified_at: 2022-03-01 03:18:42.031226
