id: A81299E2E
title: A Discourse on the Confession of Harmful Deeds Spoken by Yama Dharmarāja to
  Karma Chakme
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:18:42.029133
  last_modified_at: 2022-03-01 03:18:42.029139
