id: A81299E2E
title: The Bodhisattva’s Confession of Downfalls (Nyingma Version)
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:18:42.052784
  last_modified_at: 2022-03-01 03:18:42.052787
