id: A81299E2E
title: The Inexpressible, Ultimate Confession (Yeshe Kuchokma)
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:18:42.054503
  last_modified_at: 2022-03-01 03:18:42.054506
