id: A81299E2E
title: The Spontaneous Vajra Song of Fulfilment and Confession
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:18:42.063314
  last_modified_at: 2022-03-01 03:18:42.063317
