id: A81299E2E
title: A Practice of Fulfilment and Confession to an Ocean of Oath-bound Protectors
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:18:42.033143
  last_modified_at: 2022-03-01 03:18:42.033146
