id: A81299E2E
title: Brief Confession to the Earth Lords
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:18:42.035291
  last_modified_at: 2022-03-01 03:18:42.035294
