id: A81299E2E
title: The Ultimate Inexpressible Confession (Yeshe Kuchokma)
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:18:42.066122
  last_modified_at: 2022-03-01 03:18:42.066125
