id: A81299E2E
title: Rays of Moonlight to Dispel the Darkness of Misdeeds
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:18:42.050575
  last_modified_at: 2022-03-01 03:18:42.050578
