id: A81299E2E
title: Method of Confession based on the Four Powers
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:18:42.048958
  last_modified_at: 2022-03-01 03:18:42.048961
