id: A81299E2E
title: Daily Confession (from the Vajrapañjara Tantra)
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:18:42.036284
  last_modified_at: 2022-03-01 03:18:42.036286
