id: A81299E2E
title: The Lament of Rudra
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:18:42.055670
  last_modified_at: 2022-03-01 03:18:42.055672
