id: A81299E2E
title: Heart of Vajrasattva—The Heart of Confession, the King of Purification Practices,
  from 'The Immaculate Secret Vajrasattva'
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:18:42.047413
  last_modified_at: 2022-03-01 03:18:42.047417
