id: A81299E2E
title: Verses of Confession 'Düsum Deshekma'
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:18:42.069121
  last_modified_at: 2022-03-01 03:18:42.069124
